FROM node:14.19.1-alpine3.15 as builder
WORKDIR /
#RUN rm -rf node_modules
ADD package.json /
RUN npm install --production --registry=https://registry.npm.taobao.org
ADD . /
# 删除编译输出文件夹
RUN rm -rf cdh-web
RUN npm rebuild node-sass
RUN npm run build


FROM mirrors.myoas.com/docker/nginx:1.21.1
WORKDIR /
COPY --from=builder /cdh-web /usr/share/nginx/html/
RUN chmod 755 -R /usr/share/nginx/html